// Generated by CoffeeScript 1.6.3
(function() {
  var init, showNextExcerpt;

  showNextExcerpt = function() {
    var next_excerpt;
    next_excerpt = $(".blog-excerpt.active").next();
    $(".blog-excerpt.active").removeClass("active");
    if (next_excerpt.is(".blog-excerpt")) {
      return $(next_excerpt).addClass("active");
    } else {
      return $(".blog-excerpt").first().addClass("active");
    }
  };

  init = function() {
    var blog_excerpts;
    blog_excerpts = $(".blog-excerpt");
    console.log("found " + blog_excerpts.length);
    if (blog_excerpts.length > 0) {
      $(blog_excerpts).first().addClass("active");
    }
    console.log("doing next");
    return $(".blog-excerpt-next-link").click(showNextExcerpt);
  };

  $(document).ready(init);

}).call(this);
